[env]
TERM = "xterm-256color"

[general]
import = ["catppuccin-mocha.toml"]

[font]
normal = {family = "OpenDyslexicM Nerd Font Mono", style = "Regular"}

[cursor]
style = {shape = "Beam", blinking = "Off"}
